### ISSUE TITLE
recurring PolyglotException when rendering UI. 

### ISSUE THREAD

**Issue by sgir** [dirigiblelabs/sample-crm#1]
Hi there, 

Thanks so much for providing this example to play around with. I was retracing the steps and found these errors when running dirigible using docker. Any ideas why?

all i did was add a VARCHAR(64) field in the Account Entity which renders and i keep seeing the following error.

```
2020-07-29 13:40:00.825 [ERROR] [DirigibleClusteredScheduler_Worker-1] org.quartz.core.ErrorLogger - Job (dirigible-defined./crm/feed/Customers/AccountActivitiyFeed.job threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[quartz-2.3.2.jar:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar:na]
Caused by: org.graalvm.polyglot.PolyglotException: SyntaxError: Unnamed:23:21 Expected comma but found {
			Account: data[i].${property.feedPropertyName},
			                  ^
Unnamed:23:48 Expected an operand but found ,
			Account: data[i].${property.feedPropertyName},
			                                             ^
Unnamed:24:18 Expected ; but found {
			Date: data[i].${property.feedPropertyName},
			               ^
Unnamed:24:45 Expected an operand but found ,
			Date: data[i].${property.feedPropertyName},
			                                          ^
Unnamed:25:18 Expected ; but found {
			Name: data[i].${property.feedPropertyName},
			               ^
Unnamed:25:45 Expected an operand but found ,
			Name: data[i].${property.feedPropertyName},
			                                          ^
Unnamed:26:20 Expected ; but found {
			Status: data[i].${property.feedPropertyName}
			                 ^
Unnamed:27:2 Expected eof but found }
		});
		^

	at org.graalvm.polyglot.Context.eval(Context.java:371) ~[graal-sdk-20.0.0.jar:na]
	at org.eclipse.dirigible.engine.js.graalvm.processor.GraalVMJavascriptEngineExecutor.executeService(GraalVMJavascriptEngineExecutor.java:129) ~[dirigible-engine-javascript-graalvm-5.1.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.engine.js.graalvm.processor.GraalVMJavascriptEngineExecutor.executeServiceModule(GraalVMJavascriptEngineExecutor.java:63) ~[dirigible-engine-javascript-graalvm-5.1.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.engine.js.processor.DefaultJavascriptEngineExecutor.executeServiceModule(DefaultJavascriptEngineExecutor.java:57) ~[dirigible-engine-javascript-5.1.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.engine.api.script.ScriptEngineExecutorsManager.executeServiceModule(ScriptEngineExecutorsManager.java:42) ~[dirigible-engine-api-5.1.0-SNAPSHOT.jar:na]
	at org.eclipse.dirigible.core.scheduler.handler.JobHandler.execute(JobHandler.java:33) ~[dirigible-core-scheduler-5.1.0-SNAPSHOT.jar:na]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:na]
	... 1 common frames omitted
2020-07-29 13:40:01.286 [INFO ] [DirigibleClusteredScheduler_Worker-5] o.e.dirigible.api.v3.core.Console - File name: roles-access.json
2020-07-29 13:40:01.290 [INFO ] [DirigibleClusteredScheduler_Worker-5] o.e.dirigible.api.v3.core.Console - Length: 18
2020-07-29 13:40:01.294 [INFO ] [DirigibleClusteredScheduler_Worker-5] o.e.dirigible.api.v3.core.Console - Mime Type: application/json
2020-07-29 13:40:01.348 [INFO ] [DirigibleClusteredScheduler_Worker-5] o.e.dirigible.api.v3.core.Console - Access Definitions successfully synchronized by [ide-documents-security] Job

```

**Comment by ThuF** [comment]
To be traced in these two separate issues in the main repository:
- https://github.com/eclipse/dirigible/issues/587
- https://github.com/eclipse/dirigible/issues/588
